services:
  php:
    image: php:8.2-cli
    container_name: versecli
    working_dir: /app
    volumes:
      - ./:/app
    command: tail -f /dev/null  # Keep container running
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug,develop,coverage
      XDEBUG_START_WITH_REQUEST: yes
      XDEBUG_CLIENT_HOST: host.docker.internal
    ports:
      - "9005:9003"  # Map external 9005 to internal 9003
    tty: true

    # Xdebug setup
    build:
      context: .
      dockerfile: Dockerfile
